apiVersion: apps/v1
kind: Deployment
metadata:
  name: employee-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: employee-app
  template:
    metadata:
      labels:
        app: employee-app
    spec:
      containers:
      - name: employee-app
        image: myacrbenetta1086.azurecr.io/employee-app:v1
        ports:
        - containerPort: 3000
